apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lbrn4bbfd-go 
  janus-idp.io/tekton: lbrn4bbfd-go
  backstage.io/kubernetes-id: lbrn4bbfd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lbrn4bbfd-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  